### ISSUE TITLE
Drop xpath-rs in favor of sxd-rust?

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/xpath-rs#7]
https://github.com/shepmaster/sxd-rust

**Comment by shepmaster** [comment]
Howdy! As I'm getting closer and closer to a releasable version of SXD, I'd love to put it to the test in the real world. If you'd be so kind as to point me to the appropriate crate that uses xpath-rs, I'll give it a shot!

**Comment by bvssvni** [comment]
@shepmaster I'm not aware of any project that uses xpath-rs yet. So if nobody are using it, I'm in favor of dropping it and recommending people to use your project.

**Comment by bvssvni** [comment]
@panicbit Are you in favor of deprecating xpath-rs in favor of https://github.com/shepmaster/sxd-xpath ?

**Comment by panicbit** [comment]
@bvssvni Yeah :+1:

**Comment by bvssvni** [comment]
Added deprecated warning to README.

Closing.
